# This playbook consists of how to write a playbook.
# In playbook we have multiple play and each play has multiple tasks.

---
- hosts: web_server                  # In /etc/ansible/hosts file you have added some hosts see Installation file.
  become: yes
  user: ansible/root                 # If you have created a user add it here from which you are running this playbook.
  connection: ssh
  gather_facts: false/true           # It will not show the entire info on screen
  tasks: 
     - name: Install apache httpd  (state=present is optional)
       apt:
        name: apache2
        state: present

     - name: Update repositories cache and install "foo" package
       apt:
        name: foo
        update_cache: yes

     - name: Remove "foo" package
       apt:
         name: foo
         state: absent
...       
       
