---
- hosts: web_server                  # In /etc/ansible/hosts file you have added some hosts see Installation file.
  become: yes
  user: ansible/root                 # If you have created a user add it here from which you are running this playbook.
  connection: ssh
  gather_facts: false/true           # It will not show the entire info on screen
  tasks: 
      - name: Print the gateway for each host when defined
        debug:
           msg: System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}
        when: ansible_default_ipv4.gateway is defined

      - name: Get uptime information
        register: result
