---
- hosts: web_server                  # In /etc/ansible/hosts file you have added some hosts see Installation file.
  become: yes
  user: ansible/root                 # If you have created a user add it here from which you are running this playbook.
  connection: ssh
  gather_facts: false/true           # It will not show the entire info on screen
  tasks: 
      - name: Ensure a job that runs at 2 and 5 exists. Creates an entry like "0 5,2 * * ls -alh > /dev/null"
        cron:
           name: "check dirs"
           minute: "0"
           hour: "5,2"
           job: "ls -alh > /dev/null"

      - name: 'Ensure an old job is no longer present. Removes any job that is prefixed by "#Ansible: an old job" from the crontab'
         cron:
            name: "an old job"
             state: absent
