# This module works like copy, but in reverse.
# It is used for fetching files from remote machines and storing them locally in a file tree, organized by hostname.
# Files that already exist at dest will be overwritten if they are different than the src.

---
- hosts: web_server                  # In /etc/ansible/hosts file you have added some hosts see Installation file.
  become: yes
  user: ansible/root                 # If you have created a user add it here from which you are running this playbook.
  connection: ssh
  gather_facts: false/true           # It will not show the entire info on screen
  tasks: 
     - name: Store file into /tmp/fetched/host.example.com/tmp/somefile
       fetch:
         src: /tmp/somefile
         dest: /tmp/fetched
...       
       
