# This playbook consists of how to write a playbook.
# In playbook we have multiple play and each play has multiple tasks.

---
- hosts: web_server                                           # In /etc/ansible/hosts file you have added some hosts see Installation file.
  become: yes
  user: ansible/root                                          # If you have created a user add it here from which you are running this playbook.
  connection: ssh
  gather_facts: false/true                                    # It will not show the entire info on screen
  tasks: 
     - name: This is first task will create directory         # Add the info here about the task.
       file: path=/opt/Directory state=directory mode='0777'  # In file module there are multiple parameters are there please check on Ansible-Documentation.
                                                              # https://docs.ansible.com/ansible/2.9/modules/list_of_files_modules.html  Check on this link

     - name: This is second task will create file inside above directory
       file: path=/opt/Directory/a.txt state=touch mode='0777'           # Give your permission for this file
...       
       
