# The tempfile module creates temporary files and directories. 
# mktemp command takes different parameters on various systems, this module helps to avoid troubles related to that. 
# Files/directories created by module are accessible only by creator. 
# In case you need to make them world-accessible you need to use file module.

---
- hosts: web_server                  # In /etc/ansible/hosts file you have added some hosts see Installation file.
  become: yes
  user: ansible/root                 # If you have created a user add it here from which you are running this playbook.
  connection: ssh
  gather_facts: false/true           # It will not show the entire info on screen
  tasks: 
    - name: create temporary build directory
      tempfile:
       state: directory
       suffix: build

    - name: create temporary file
      tempfile:
       state: file
       suffix: temp
      register: tempfile_1

    - name: use the registered var and the file module to remove the temporary file
      file:
        path: "{{ tempfile_1.path }}"
        state: absent
      when: tempfile_1.path is defined
...       
       
